// pacman-maze.ts — the authored "Pac-Man" mode maze and its assembly into the ROM stage format.
//
// Stage format: 13×13 blocks of 16×16 px, 14 nibbles per row (13 blocks + padding,
// since the ROM does an extra INC of the counter), even index — high nibble, stride 7 bytes = 91.
// Block codes (tbl_DACB): 0x09 = concrete (wall), 0x0D = empty (corridor).
//
// The maze is generated by a deterministic DFS over "cells" (odd coordinates) plus
// an open ring path along the perimeter; guaranteed connected. We don't touch the base area.
//
// Relative path: ./emulator-core/features/pacman-maze.ts

export const BLOCK_WALL = 0x09; // full concrete
export const BLOCK_EMPTY = 0x0d; // full empty block
export const MAZE_SIZE = 13;
export const STAGE_BYTES = 91;
export const DOT_TILE = 0x69; // small centered square (dot) from CHR bank1

// Deterministic LCG (no Math.random — architectural test).
function lcg(seed: number): () => number {
  let s = seed >>> 0;
  return () => {
    s = (Math.imul(s, 1664525) + 1013904223) >>> 0;
    return s >>> 0;
  };
}

const BASE_R0 = 11,
  BASE_R1 = 12,
  BASE_C0 = 5,
  BASE_C1 = 7;

function isBaseBlock(r: number, c: number): boolean {
  return r >= BASE_R0 && r <= BASE_R1 && c >= BASE_C0 && c <= BASE_C1;
}

// Maze generation: true = wall. Cells are odd (r,c) 1..11; DFS carves passages.
function generate(): boolean[] {
  const N = MAZE_SIZE;
  const wall = new Array<boolean>(N * N).fill(true);
  const idx = (r: number, c: number) => r * N + c;
  const carve = (r: number, c: number) => {
    wall[idx(r, c)] = false;
  };

  // Open ring path along the perimeter (tunnels/spawns).
  for (let i = 0; i < N; i++) {
    carve(0, i);
    carve(N - 1, i);
    carve(i, 0);
    carve(i, N - 1);
  }
  // Maze cells at odd coordinates.
  for (let r = 1; r < N; r += 2) for (let c = 1; c < N; c += 2) carve(r, c);

  // DFS (perfect maze) over cells with a fixed seed.
  const rnd = lcg(0x9e3779b9);
  const visited = new Set<number>();
  const stack: [number, number][] = [[1, 1]];
  carve(1, 1);
  visited.add(idx(1, 1));
  while (stack.length) {
    const [r, c] = stack[stack.length - 1];
    const all: [number, number][] = [
      [r - 2, c],
      [r + 2, c],
      [r, c - 2],
      [r, c + 2],
    ];
    const dirs = all.filter(([nr, nc]) => nr >= 1 && nr < N - 1 && nc >= 1 && nc < N - 1 && !visited.has(idx(nr, nc)));
    if (dirs.length === 0) {
      stack.pop();
      continue;
    }
    const [nr, nc] = dirs[rnd() % dirs.length];
    carve((r + nr) >> 1, (c + nc) >> 1); // carve the wall between cells
    carve(nr, nc);
    visited.add(idx(nr, nc));
    stack.push([nr, nc]);
  }

  // Base area — always a corridor (the ROM patch walls it off).
  for (let r = BASE_R0; r <= BASE_R1; r++) for (let c = BASE_C0; c <= BASE_C1; c++) carve(r, c);

  return wall;
}

const GRID: boolean[] = generate();

/** Wall in the block. */
export function isWallBlock(r: number, c: number): boolean {
  if (r < 0 || c < 0 || r >= MAZE_SIZE || c >= MAZE_SIZE) return true;
  return GRID[r * MAZE_SIZE + c];
}

export function blockCode(r: number, c: number): number {
  return isWallBlock(r, c) ? BLOCK_WALL : BLOCK_EMPTY;
}

/** 91 stage bytes (13 rows × 7 bytes; 14 nibbles per row: 13 blocks + padding). */
export function buildStageBytes(): Uint8Array {
  const out = new Uint8Array(STAGE_BYTES);
  let k = 0;
  for (let r = 0; r < MAZE_SIZE; r++) {
    for (let c = 0; c <= MAZE_SIZE; c++) {
      const code = c < MAZE_SIZE ? blockCode(r, c) & 0x0f : 0;
      const bi = k >> 1;
      out[bi] = k % 2 === 0 ? (out[bi] & 0x0f) | (code << 4) : (out[bi] & 0xf0) | code;
      k++;
    }
  }
  return out;
}

export interface Bomb {
  off: number;
  id: number;
}
/** Field offset of the top-left cell of a block (2+2c, 2+2r). */
export function blockCellOff(r: number, c: number): number {
  return (2 + 2 * r) * 32 + (2 + 2 * c);
}
export function blockCenterOff(r: number, c: number): number {
  return blockCellOff(r, c);
}

// Bombs (P2) — always in the four corners; all are "bomb" (grenade, id 4).
export const BOMBS: Bomb[] = [
  { r: 0, c: 0, id: 4 },
  { r: 0, c: 12, id: 4 },
  { r: 12, c: 0, id: 4 },
  { r: 12, c: 12, id: 4 },
].map((b) => ({ off: blockCenterOff(b.r, b.c), id: b.id }));

/** Dot cells: all corridor blocks except the base and bomb cells (a bomb is BG 2×2). */
export function dotCells(): number[] {
  const out: number[] = [];
  const bombSet = new Set<number>();
  for (const b of BOMBS) {
    bombSet.add(b.off);
    bombSet.add(b.off + 1);
    bombSet.add(b.off + 32);
    bombSet.add(b.off + 33);
  }
  for (let r = 0; r < MAZE_SIZE; r++) {
    for (let c = 0; c < MAZE_SIZE; c++) {
      if (isWallBlock(r, c) || isBaseBlock(r, c)) continue;
      const off = blockCellOff(r, c);
      if (bombSet.has(off)) continue;
      out.push(off);
    }
  }
  return out;
}

export default { buildStageBytes, dotCells, BOMBS, DOT_TILE, STAGE_BYTES, isWallBlock };
